export const CONDITIONS = [
  {
    slug: 'anxiety',
    name: 'Anxiety Disorders',
    icon: 'Wind',
    tagline: 'GAD, panic disorder, social anxiety',
    detail: 'Generalized anxiety disorder (GAD), panic disorder, social anxiety, and adjustment disorder with anxiety are all recognized FMLA-qualifying serious health conditions when symptoms substantially limit your ability to perform essential job functions.',
    programs: ['FMLA', 'Paid Family Leave', 'Short-Term Disability', 'ADA'],
  },
  {
    slug: 'depression',
    name: 'Depression',
    icon: 'CloudRain',
    tagline: 'Major depressive disorder, persistent depressive disorder',
    detail: 'Major depressive disorder, persistent depressive disorder, postpartum depression, and seasonal affective disorder are FMLA-qualifying conditions. Mental health is treated equally to physical health under federal law.',
    programs: ['FMLA', 'Paid Family Leave', 'Short-Term Disability', 'ADA'],
  },
  {
    slug: 'migraines',
    name: 'Chronic Migraines',
    icon: 'Zap',
    tagline: 'Recurrent, severe, or treatment-resistant',
    detail: 'Chronic migraine (15+ headache days per month) and treatment-resistant migraine often qualify for FMLA — especially as intermittent leave for flare-ups and treatment.',
    programs: ['FMLA', 'ADA', 'Short-Term Disability'],
  },
  {
    slug: 'chronic-pain',
    name: 'Chronic Pain',
    icon: 'Activity',
    tagline: 'Back pain, fibromyalgia, joint conditions',
    detail: 'Chronic back pain, fibromyalgia, rheumatoid arthritis, and other chronic pain conditions qualify when they substantially limit your ability to perform essential job functions.',
    programs: ['FMLA', 'Short-Term Disability', 'ADA'],
  },
  {
    slug: 'pregnancy',
    name: 'Pregnancy & Postpartum',
    icon: 'Baby',
    tagline: 'High-risk pregnancy, postpartum depression, maternity leave',
    detail: 'Pregnancy, prenatal care, childbirth, and postpartum recovery (including postpartum depression) all qualify for FMLA. Most states with paid family leave include parental bonding time.',
    programs: ['FMLA', 'Paid Family Leave', 'Short-Term Disability'],
  },
  {
    slug: 'cancer',
    name: 'Cancer',
    icon: 'Ribbon',
    tagline: 'Diagnosis, treatment, recovery',
    detail: 'Cancer diagnosis, chemotherapy, radiation, surgery, and recovery all qualify for FMLA. Treatment-related leave can be intermittent (e.g., leave for each chemo session).',
    programs: ['FMLA', 'Short-Term Disability', 'Paid Family Leave', 'ADA'],
  },
  {
    slug: 'autoimmune',
    name: 'Autoimmune Disease',
    icon: 'Shield',
    tagline: 'Lupus, MS, rheumatoid arthritis, Crohn\'s',
    detail: 'Lupus, multiple sclerosis, rheumatoid arthritis, Crohn\'s disease, ulcerative colitis, and other autoimmune conditions qualify — often as intermittent FMLA for flares and infusions.',
    programs: ['FMLA', 'Short-Term Disability', 'ADA'],
  },
  {
    slug: 'diabetes',
    name: 'Diabetes',
    icon: 'Droplet',
    tagline: 'Type 1, Type 2, gestational',
    detail: 'Type 1 and Type 2 diabetes qualify when complications limit work — including frequent monitoring needs, insulin management, or diabetic neuropathy.',
    programs: ['FMLA', 'ADA'],
  },
  {
    slug: 'asthma-copd',
    name: 'Asthma / COPD',
    icon: 'Wind',
    tagline: 'Severe, exacerbations',
    detail: 'Severe asthma and COPD qualify when exacerbations require treatment that prevents work, or when ongoing management substantially limits your ability to perform essential job functions.',
    programs: ['FMLA', 'ADA'],
  },
  {
    slug: 'cardiovascular',
    name: 'Cardiovascular',
    icon: 'Heart',
    tagline: 'Heart conditions requiring treatment or recovery',
    detail: 'Heart attack recovery, cardiac surgery, congestive heart failure, and arrhythmias requiring treatment qualify for FMLA leave during recovery and ongoing management.',
    programs: ['FMLA', 'Short-Term Disability', 'ADA'],
  },
  {
    slug: 'ptsd',
    name: 'PTSD',
    icon: 'AlertTriangle',
    tagline: 'Trauma-related conditions',
    detail: 'Post-traumatic stress disorder is a recognized FMLA-qualifying serious health condition. Leave can be continuous (intensive treatment) or intermittent (therapy appointments, flare-ups).',
    programs: ['FMLA', 'Short-Term Disability', 'ADA'],
  },
  {
    slug: 'family-care',
    name: 'Caring for a Family Member',
    icon: 'Users',
    tagline: 'Serious illness of spouse, child, or parent',
    detail: 'You can take FMLA leave to care for a spouse, child (under 18 or incapable of self-care), or parent with a serious health condition. Form WH-380-F applies.',
    programs: ['FMLA', 'Paid Family Leave'],
  },
];

export function getCondition(slug) {
  return CONDITIONS.find((c) => c.slug === slug);
}
